### ISSUE TITLE
Pin server version

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-jdtls#12] opened 2021-05-27 22:11 UTC
Instead of always getting the latest version, please pin the server version.

When the download site has problems and there happens to be a new version, all users are stuck with a hanging download.

**Comment by LDAP** [comment] 2021-06-14 15:30
Is this really a solution? What if we bump the server version and then the site has problems?

**Comment by MrSnugglesGH** [comment] 2021-08-04 16:19
I'd like to report my experience using LSP-jdtls on August 1st, 2021. Note, however, that today (August 4th, 2021) I no longer experience any problems. If the following problem appears again in the future or someone else experiences the same problem, this may be helpful to know as a workaround is given at the end of this comment.<br /><br /><br />

**Problem.** Opening any .java file leads to _completely unpredictable behavior_ of LSP-jdtls. 

Basically, I can expect one of the following three types of behavior when I open any .java file. 
1. _Everything works as expected_ - Everything is underlined as it should be, pop-up windows are displayed on hover, Definition & References & Rename work and so on...
2.  _It works... sort of..._ - Everything works as in 1. However, there is considerable lag in the functionality of LSP-jdtls. Pop-up windows take a long time to show up and elements of code remain underlined even though my mouse is no longer hovering over the same element. (In the picture below my mouse is hovering over '...abs...' in line 16. However, 'GaussianElimination' in line 5 is underlined)
![worksButIsBuggy](https://user-images.githubusercontent.com/88436666/128206225-344d24dd-c8cf-42f6-8a72-4b52d3b2a686.png)

3. _Nothing works_ - As if I haven't installed LSP-jdtls in the first place. (Notice that in the picture below there is no 'jdtls' in the status bar)
![doesntWork](https://user-images.githubusercontent.com/88436666/128206244-a2b02cb1-89e2-4380-9ecd-421e9966c895.png)


Which of the aforementioned behaviors I get seems completely chosen at random (even if I keep opening and closing the same file over and over again I get inconsistent experience).<br /><br /><br />

**Reproducing the problem.** Do a clean install of Sublime Text 4 with _'factory settings'_ (or delete Sublime-Text in ~/.config folder). Then, install:

1. Package Control
2. LSP
3. LSP-jdtls 

Save a .java file on your Desktop (For example use java code at the end of the page: https://www.algorithm-archive.org/contents/gaussian_elimination/gaussian_elimination.html --- you may have to select Java from a list of all available programming languages in the top bar of the page).

Open the file you saved on your Desktop. Test the functionality of LSP-jdtls. Close the file and repeat this process as many times as you'd like. <br /><br /><br />

**Solution (workaround).** _Disconnecting from the internet before opening Sublime Text 4 completely solves the issue._ LSP-jdtls works as it was supposed to. No more unpredictable behavior every time I open .java file. Moreover, the behavior of LSP-jdtls is smooth and no longer are elements of code underlined that are no longer hovered over. <br /><br /><br />

**Additional info.** I am using Linux Mint 20.2 and running `java --version` in terminal gives:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```
<br /><br /><br />
This comment is a summary of a discussion between me and @rwols on August 1st, 2021 on Sublime Text Discord server.

**Closed** 2022-07-28 07:10 UTC

**Comment by rchl** [comment] 2022-07-28 08:35
Pinning is also useful because it allows you to review the changes done to the server when updating it and either add new settings, remove removed ones or address breaking changes.
