### ISSUE TITLE
jdtls exits with status code 1

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP-jdtls#2] opened 2020-11-23 14:38 UTC
After opening a java file:
![grafik](https://user-images.githubusercontent.com/8215084/99974672-8f2ce200-2da1-11eb-8090-13b01bbb589e.png)

The console does not log any errors/warnings.

**Comment by rwols** [comment] 2020-11-23 14:40
You need at least JDK 11.

What version of Sublime Text are you running?

**Comment by LDAP** [comment] 2020-11-23 15:08
I am running JDK 15.
Sublime Text Build 4093.

**Comment by rwols** [comment] 2020-11-23 15:11
Please run "LSP: Troubleshoot Server" from the command palette and choose jdtls. Paste the output here. (you may need to open a new window if jdtls was disabled previously).

**Comment by rwols** [comment] 2020-11-23 15:12
Also, make sure you have `JAVA_HOME` set in your environment variables.

**Comment by LDAP** [comment] 2020-11-23 15:27
`JAVA_HOME` is set.
Output of "LSP: Troubleshoot Server":

# Troubleshooting: jdtls
## Version
 - LSP: 1.1.0
 - Sublime Text: 4093
## Server Test Run
 - exit code: -1
 - output
```
[WinError 87] Falscher Parameter
```
## Server Configuration
 - command
```json
[
  "${java_executable}", 
  "--add-modules=ALL-SYSTEM", 
  "--add-opens", 
  "java.base/java.util=ALL-UNNAMED", 
  "--add-opens", 
  "java.base/java.lang=ALL-UNNAMED", 
  "-Declipse.application=org.eclipse.jdt.ls.core.id1", 
  "-Dosgi.bundles.defaultStartLevel=4", 
  "-Declipse.product=org.eclipse.jdt.ls.core.product", 
  "-Dfile.encoding=UTF-8", 
  "-DwatchParentProcess=${watch_parent_process}", 
  "-noverify", 
  "-Xmx1G", 
  "-XX:+UseG1GC", 
  "-XX:+UseStringDeduplication", 
  "-jar", 
  "${packages}/LSP-jdtls/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar", 
  "-configuration", 
  "${packages}/LSP-jdtls/config_${jdtls_platform}", 
  "-data", 
  "${storage_path}/LSP-jdtls"
]
```
 - shell command
```sh
${java_executable} --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=UTF-8 -DwatchParentProcess=${watch_parent_process} -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar ${packages}/LSP-jdtls/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar -configuration ${packages}/LSP-jdtls/config_${jdtls_platform} -data ${storage_path}/LSP-jdtls
```
 - selector
```
source.java
```
 - priority_selector
```
source.java
```
 - init_options
```json
{}
```
 - settings
```json
{
  "java": {
    "autobuild": {
      "enabled": true
    }, 
    "codeGeneration": {
      "generateComments": false, 
      "hashCodeEquals": {
        "useInstanceof": false, 
        "useJava7Objects": false
      }, 
      "toString": {
        "codeStyle": "STRING_CONCATENATION", 
        "limitElements": 0, 
        "listArrayContents": true, 
        "skipNullValues": false, 
        "template": "${object.className} [${member.name()}=${member.value}, ${otherMembers}]"
      }, 
      "useBlocks": false
    }, 
    "completion": {
      "enabled": true, 
      "favoriteStaticMembers": [
        "org.junit.Assert.*", 
        "org.junit.Assume.*", 
        "org.junit.jupiter.api.Assertions.*", 
        "org.junit.jupiter.api.Assumptions.*", 
        "org.junit.jupiter.api.DynamicContainer.*", 
        "org.junit.jupiter.api.DynamicTest.*", 
        "org.mockito.Mockito.*", 
        "org.mockito.ArgumentMatchers.*", 
        "org.mockito.Answers.*"
      ], 
      "filteredTypes": [
        "java.awt.*", 
        "com.sun.*"
      ], 
      "guessMethodArguments": false, 
      "importOrder": [
        "java", 
        "javax", 
        "com", 
        "org"
      ], 
      "maxResults": 0, 
      "overwrite": true
    }, 
    "configuration": {
      "checkProjectSettingsExclusions": true, 
      "maven": {
        "globalSettings": null, 
        "userSettings": null
      }, 
      "runtimes": [], 
      "updateBuildConfiguration": "interactive"
    }, 
    "contentProvider": {
      "preferred": null
    }, 
    "errors": {
      "incompleteClasspath": {
        "severity": "warning"
      }
    }, 
    "foldingRange": {
      "enabled": false
    }, 
    "format": {
      "comments": {
        "enabled": true
      }, 
      "enabled": true, 
      "onType": {
        "enabled": true
      }, 
      "settings": {
        "profile": null, 
        "url": null
      }
    }, 
    "home": null, 
    "implementationsCodeLens": {
      "enabled": false
    }, 
    "import": {
      "exclusions": [
        "**/node_modules/**", 
        "**/.metadata/**", 
        "**/archetype-resources/**", 
        "**/META-INF/maven/**"
      ], 
      "gradle": {
        "arguments": null, 
        "enabled": true, 
        "home": null, 
        "java": {
          "home": null
        }, 
        "jvmArguments": null, 
        "offline": {
          "enabled": false
        }, 
        "user": {
          "home": null
        }, 
        "version": null, 
        "wrapper": {
          "enabled": true
        }
      }, 
      "maven": {
        "enabled": true
      }
    }, 
    "imports": {
      "gradle": {
        "wrapper": {
          "checksums": []
        }
      }
    }, 
    "jdt": {
      "ls": {
        "vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m"
      }
    }, 
    "maven": {
      "downloadSources": false, 
      "updateSnapshots": false
    }, 
    "maxConcurrentBuilds": 1, 
    "progressReports": {
      "enabled": true
    }, 
    "project": {
      "importHint": true, 
      "importOnFirstTimeStartup": "interactive", 
      "referencedLibraries": [
        "lib/**/*.jar"
      ], 
      "resourceFilters": [
        "node_modules", 
        ".git"
      ]
    }, 
    "refactor": {
      "renameFromFileExplorer": "prompt"
    }, 
    "references": {
      "includeAccessors": true
    }, 
    "referencesCodeLens": {
      "enabled": false
    }, 
    "saveActions": {
      "organizeImports": false
    }, 
    "selectionRange": {
      "enabled": true
    }, 
    "semanticHighlighting": {
      "enabled": true
    }, 
    "server": {
      "launchMode": "Hybrid"
    }, 
    "showBuildStatusOnStart": {
      "enabled": false
    }, 
    "signatureHelp": {
      "enabled": false
    }, 
    "sources": {
      "organizeImports": {
        "starThreshold": 99, 
        "staticStarThreshold": 99
      }
    }, 
    "templates": {
      "fileHeader": [], 
      "typeComment": []
    }, 
    "trace": {
      "server": "off"
    }
  }
}
```
 - env
```json
{}
```

## Active view
 - File name
```
C:\Users\Lucas Alber\Desktop\TaskA\edu\kit\informatik\MagicSquare.java
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Java/Java.sublime-syntax"
}
```
 - base scope
```
source.java
```

## Project / Workspace
 - folders
```json
[
  "C:\\Users\\Lucas Alber\\Desktop\\TaskA"
]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "clangd": {
      "enabled": true
    }
  }
}
```
## System PATH
 - C:\ProgramData\Anaconda3
 - C:\ProgramData\Anaconda3\Library\mingw-w64\bin
 - C:\ProgramData\Anaconda3\Library\usr\bin
 - C:\ProgramData\Anaconda3\Library\bin
 - C:\ProgramData\Anaconda3\Scripts
 - C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\bin
 - C:\Windows\system32
 - C:\Windows
 - C:\Windows\System32\Wbem
 - C:\Windows\System32\WindowsPowerShell\v1.0\
 - C:\Windows\System32\OpenSSH\
 - C:\Program Files (x86)\Common Files\Acronis\SnapAPI\
 - C:\Program Files (x86)\Common Files\Acronis\VirtualFile\
 - C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\
 - C:\Program Files (x86)\Common Files\Acronis\FileProtector\
 - C:\Program Files (x86)\Common Files\Acronis\FileProtector64\
 - C:\Program Files\Docker\Docker\resources\bin
 - C:\ProgramData\DockerDesktop\version-bin
 - C:\Program Files\Git\cmd
 - C:\Users\Lucas Alber\AppData\Local\Microsoft\WindowsApps
 - C:\Program Files\Sublime Text
 - D:\Local_Repositories\windows-dev-tools\wsl-wrapper
 - D:\Local_Repositories\windows-dev-tools\bins\texlive\bin\win32
 - D:\Local_Repositories\windows-dev-tools\bins\LLVM\bin
 - D:\Local_Repositories\windows-dev-tools\bins\node
 -

**Comment by rwols** [comment] 2020-11-23 15:28
```
C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\bin
```

I'm guessing this is `JAVA_HOME`. It should be

```
C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot
```

(without the extra `\bin`)

**Comment by LDAP** [comment] 2020-11-23 15:30
Sorry:
´´´
C:\Users\Lucas Alber>echo %JAVA_HOME%
C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\
´´´´

**Comment by rwols** [comment] 2020-11-23 15:53
But it doesn't seem to be in your %PATH%. Can you log out and log in to make sure that the env vars are updated?

**Comment by LDAP** [comment] 2020-11-23 15:57
> 
> 
> But it doesn't seem to be in your %PATH%. Can you log out and log in to make sure that the env vars are updated?

%JAVA_HOME% is never in PATH as far as I know

**Comment by rwols** [comment] 2020-11-23 16:08
Right, I got confused about %PATH% and %JAVA_HOME% :)

I'm starting to think that the problem is elsewhere then. Can you try running this from a command-line? It is a very long command, unfortunately

```
java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=UTF-8 -DwatchParentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:/PATH/TO/SUBLIME/PACKAGES/LSP-jdtls/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar -configuration C:/PATH/TO/SUBLIME/PACKAGES/LSP-jdtls/config_win -data C:\Temp
```

Replace `C:/PATH/TO/SUBLIME/PACKAGES` with your actual path to your packages folder (Preferences > Browse Packages...)

```
[WinError 87] Falscher Parameter
```

this seems to suggest one of the parameters is incorrect.

**Comment by LDAP** [comment] 2020-11-23 16:14
I think we are on the right path. The `plugins` is missing in LSP-jdtls.

**Comment by rwols** [comment] 2020-11-23 16:17
Right. This repository is just a "builder" that builds a release, sing the make.sh script.

To get the actual package that you put in your Packages/ directory, download a release here: https://github.com/sublimelsp/LSP-jdtls/releases/tag/v0.0.1

**Comment by LDAP** [comment] 2020-11-23 16:30
Alright. That means installing via Package Control by adding the repo does not work?

**Comment by rwols** [comment] 2020-11-23 16:33
That is correct. I should add a paragraph in the readme about this.

**Comment by LDAP** [comment] 2020-11-23 16:34
Okey its working now :) 
Maybe download and extract the files in the future automatically when the plugin is loaded

**Comment by rwols** [comment] 2020-11-23 16:37
Once I do add it to package control, it will be installable as such: https://github.com/sublimelsp/repository/pull/35

There's just a question of whether package control will correctly handle HTTP redirections:
https://github.com/wbond/package_control/issues/1502
https://github.com/wbond/package_control/issues/1503
https://github.com/wbond/package_control/pull/1510

**Comment by LDAP** [comment] 2020-11-23 16:42
> 
> 
> That is correct. I should add a paragraph in the readme about this.

I will leave this issue open for now for people to find it in case they missed that too.

**Comment by rwols** [comment] 2020-11-28 14:00
I hope 1e0ad49960bd72b3f321ce489909da2bc50f2d05 adds enough explanation on how to install this.

**Closed by rwols** 2020-11-28 14:00 UTC
